"""add reason column

Revision ID: bd7e1852b94e
Revises: 5351b5509b48
Create Date: 2026-09-24 16:01:14.841514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7e1852b94e'
down_revision: Union[str, Sequence[str], None] = '5351b5509b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lunch_statuses', sa.Column('reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lunch_statuses', 'reason')
    # ### end Alembic commands ###
