"""add app_settings table for runtime-editable cutoff

Revision ID: d3339b397968
Revises: e83e3ae18d3f
Create Date: 2026-08-24 10:42:37.757422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3339b397968'
down_revision: Union[str, Sequence[str], None] = 'e83e3ae18d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('cutoff_hour', sa.Integer(), nullable=False),
                    sa.Column('cutoff_minute', sa.Integer(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
