"""add phone number to users

Revision ID: e83e3ae18d3f
Revises: 
Create Date: 2026-08-24 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e83e3ae18d3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: hand-corrected. The autogenerated version of this file only
    # did op.add_column('users', ...), which assumed a 'users' table
    # already existed from an earlier migration — but this file sits at
    # the base of the chain (down_revision=None), so nothing had created
    # it yet. Rewritten to create the full schema (users, with
    # phone_number already included, plus lunch_statuses) in one step.
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('password_hash', sa.String(
                        length=255), nullable=True),
                    sa.Column('auth_provider', sa.Enum('password', 'google',
                                                       name='authprovider'), nullable=False),
                    sa.Column('role', sa.Enum('employee', 'superadmin',
                                              name='userrole'), nullable=False),
                    sa.Column('status', sa.Enum('pending', 'active',
                                                'rejected', name='userstatus'), nullable=False),
                    sa.Column('profile_picture_url', sa.String(
                        length=500), nullable=True),
                    sa.Column('phone_number', sa.String(
                        length=20), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('lunch_statuses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('is_having_lunch', sa.Boolean(), nullable=False),
                    sa.Column('day_type', sa.String(
                        length=20), nullable=False),
                    sa.Column('locked_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
                    )
    op.create_index(op.f('ix_lunch_statuses_date'),
                    'lunch_statuses', ['date'], unique=False)
    op.create_index(op.f('ix_lunch_statuses_id'),
                    'lunch_statuses', ['id'], unique=False)
    op.create_index(op.f('ix_lunch_statuses_user_id'),
                    'lunch_statuses', ['user_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_lunch_statuses_user_id'),
                  table_name='lunch_statuses')
    op.drop_index(op.f('ix_lunch_statuses_id'), table_name='lunch_statuses')
    op.drop_index(op.f('ix_lunch_statuses_date'), table_name='lunch_statuses')
    op.drop_table('lunch_statuses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')

    # Dropping a table does NOT drop the PostgreSQL ENUM types backing
    # its Enum columns — without this, a downgrade followed by an
    # upgrade fails with "type already exists".
    postgresql.ENUM(name="authprovider").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="userrole").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="userstatus").drop(op.get_bind(), checkfirst=True)
